name = "PDEHats"
uuid = "cce5857c-8ae2-4c47-a1bc-12cdfec00c24"
authors = ["James Amarel <jlamarel@lanl.gov>"]
version = "0.0.7"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MakiePublication = "dde8697e-0d61-460d-88dd-856f66710dd1"
NCCL = "3fe64909-d7a1-4096-9b7d-7a0f12cf0f6b"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegularizationTools = "29dad682-9a27-4bc3-9c72-016788665182"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ADTypes = "1.18.0"
AbstractFFTs = "1.5.0"
CairoMakie = "0.15.6"
ChainRulesCore = "1.26.0"
ComponentArrays = "0.15.30"
ConcreteStructs = "0.2.3"
DataDeps = "0.7.13"
DataInterpolations = "8.8.0"
Dates = "1.11.0"
DrWatson = "2.19.1"
ForwardDiff = "1.0.0"
JLD2 = "0.6.2"
JuliaFormatter = "1.0.62"
Krylov = "0.10.2"
KrylovKit = "0.10.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
LinearOperators = "2.11.0"
Lux = "=1.24"
LuxCUDA = "0.3.4"
MLDataDevices = "1.15.0"
MLUtils = "0.4.8"
MPI = "0.20.23"
MPIPreferences = "0.1.11"
MakiePublication = "0.4.3"
NCCL = "0.1.2"
NCDatasets = "0.14.10"
NNlib = "0.9.31"
Optimisers = "0.4.6"
Pkg = "1.11.0"
Printf = "1.11.0"
Random = "1.11.0"
RegularizationTools = "0.6.0"
Setfield = "1.1.2"
SharedArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.8"
Test = "1.11.0"
Tullio = "0.3.8"
UUIDs = "1.11.0"
Zygote = "0.7.10"
julia = "=1.11.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
